### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by shankarjai2525** [konveyor/tackle-ui#23]
After cloning the repository, I ran the "docker-compose up" command and I got this error.
I'm not able to start the UI.
![Screen Shot 2021-03-12 at 4 39 22 PM](https://user-images.githubusercontent.com/34311842/111006125-d095cd00-8351-11eb-8d94-364a17e04a10.png)

**Comment by carlosthe19916** [comment]
@shankarjai2525 Thanks for reporting this, it seems that the latest image of the project `tacke-controls` is not working properly. @mrizzi could you please take a look at the error, it seems to be a problem introduced with the Tags/TagTypes. Here is the log:

```
controls_1                  | 2021-03-13 06:43:11,160 ERROR [org.fly.cor.int.com.DbMigrate] (main) Migration of schema "public" to version "20210309.4 - insert tag" failed! Changes successfully rolled back.
controls_1                  | 2021-03-13 06:43:11,162 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.postgresql.util.PSQLException: ERROR: insert or update on table "tag" violates foreign key constraint "fkq664i9aw1wjdlptk0q5dapim7"
controls_1                  |   Detail: Key (tagtype_id)=(19) is not present in table "tag_type".
controls_1                  |   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
controls_1                  |   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
controls_1                  |   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
controls_1                  |   at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
controls_1                  |   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
controls_1                  |   at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
controls_1                  |   at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
controls_1                  |   at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
controls_1                  |   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
controls_1                  |   at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:232)
controls_1                  |   at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
controls_1                  |   at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
controls_1                  |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
controls_1                  |   at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
controls_1                  |   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78)
controls_1                  |   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67)
controls_1                  |   at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
controls_1                  |   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:421)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:328)
controls_1                  |   at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:325)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191)
controls_1                  |   at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73)
controls_1                  |   at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
controls_1                  |   at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
controls_1                  |   at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
controls_1                  |   at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
controls_1                  |   at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
controls_1                  |   at org.flywaydb.core.Flyway.execute(Flyway.java:570)
controls_1                  |   at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
controls_1                  |   at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:65)
controls_1                  |   at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions-1520831253.deploy_0(FlywayProcessor$createBeansAndStartActions-1520831253.zig:84)
controls_1                  |   at io.quarkus.deployment.steps.FlywayProcessor$createBeansAndStartActions-1520831253.deploy(FlywayProcessor$createBeansAndStartActions-1520831253.zig:40)
controls_1                  |   at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:773)
controls_1                  |   at io.quarkus.runtime.Application.start(Application.java:90)
controls_1                  |   at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
controls_1                  |   at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
controls_1                  |   at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
controls_1                  |   at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
controls_1                  |   at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

**Comment by mrizzi** [comment]
Hi @shankarjai2525, thanks for reporting this.
Now the issue is fixed and in some minutes a new container image will be available.
If you want to check, browse this page https://quay.io/repository/konveyor/tackle-controls?tab=tags

I'm curious so I hope it's fine if I ask you some questions.
Are you trying to run the tackle-ui to use the tackle application?
Or are you interested in contributing as a developer and so trying to run locally?
Or maybe both?

**Comment by shankarjai2525** [comment]
Hi @mrizzi ,
I wanted to use the tool to migrate a monolithic application to kubernetes. Curious to see the output. I can contribute too, if there is anything. Let me try it out.

**Comment by mrizzi** [comment]
Thanks @shankarjai2525 for the info.
The tackle project is still at a very early stage right now so it won't help you a lot because the main features have not been implemented yet.
If I can try to help you, I would suggest you to give a try to another tool we develop, [windup](https://github.com/windup), which can help you in migrating, mainly, Java applications (which I don't know if it's your case).
Windup is released downstream as Migration Toolkit for Applications and it's available for download with docs and more info at https://developers.redhat.com/products/mta/.
You can try the Web Console with the `Containerization` target that will evaluate your Java application with a comprehensive set of cloud and container readiness rules to understand how "healthy" the application will run in a cloud environment.
